title: CVERequest
markdown: kramdown
defaults:
  - scope:
      path: ""
    values:
      layout: default
exclude:
  - cnblogs_session.json
  - summary.json
  - summary.local.json
  - summary.local_feishu.json
  - summary.github.json
